### ISSUE TITLE
need helps

### ISSUE THREAD

**Issue by yanboyang713** [pacman-repo-builder/pacman-repo-builder#53]
Hello,

Currently, I want to set up my own arch Linux repo on GitHub. I guess this project may be useful for creating my own repo. Do your guys have got something like a step-by-step guide? I can follow?

https://www.yanboyang.com/archlinuxpackagerepository/

Currently, I need to Build signed packages manually and push them to the repo.

Thanks for your help.

**Comment by KSXGitHub** [comment]
You just need to put together a `build-pacman-repo.yaml` file and a bunch of PKGBUILDs and let this tool create a local repo for you. After that, you may upload the repo to whatever web server you see fit. Just remember to not execute this tool directly on your machine without proper sandbox (Docker or VM). Also make sure to read the README.md file carefully.

This tool does not create signed packages, because all my use-cases rely on a centralized hosting provider (GitHub), so there's no need for unknown mirrors.

**Comment by yanboyang713** [comment]
Hello @KSXGitHub 
Thanks for your helps.

**Comment by ReenigneArcher** [comment]
> This tool does not create signed packages

@KSXGitHub is this statement still true? Would it be difficult to add a CLI arg to allow signing?

**Comment by KSXGitHub** [comment]
@ReenigneArcher It's still true. But if you want to create a PR, then I'll welcome you. Be aware that it would take a long while for me to review and merge (I'm currently busy), so you may as well maintain your own fork.
