### ISSUE TITLE
Facing another issue about Installing missing dependencies

### ISSUE THREAD

**Issue by yanboyang713** [pacman-repo-builder/pacman-repo-builder#55]
Hello @KSXGitHub 

Good day to you,

I facing another issue about Installing missing dependencies when Installing missing dependencies.
On *global-settings*, I have done set *install-missing-dependencies: true*
Do you know any reasons? Thanks

Error MSG:
```
🛈 Installing missing dependencies from sync database...
⚠ No such file or directory (os error 2)
```
Full logs:
```
==== PACKAGE ====

🛈 pkgbase:           meta-emacs
🛈 pkgname:           meta-emacs
🛈 source directory:  members/meta-emacs
🛈 target repository: Meta-Scientific-repository/repo/meta-scientific.db.tar.gz

🛈 Checking for missing dependencies...
🛈 Missing dependencies: emacs ripgrep fd shellcheck libvterm libvoikko hspell nuspell hunspell aspell aspell-en pandoc emacs-pdf-tools-git mu mbsync-git lcms2 libasound.so libfontconfig.so libfreetype.so libgdk-3.so libgdk_pixbuf-2.0.so libgif.so libgpm.so libgtk-3.so libharfbuzz.so libice libjpeg.so libotf libpango-1.0.so libpng librsvg-2.so libsm libtiff.so libxfixes m17n-lib libgccjit cargo asciidoctor jq rust ghc-libs haskell-aeson haskell-diff haskell-quickcheck haskell-regex-tdfa ghc uusi python qt6-webengine cmake catch2 haskell-glob haskell-juicypixels haskell-sha haskell-aeson-pretty haskell-attoparsec haskell-base64 haskell-blaze-html haskell-blaze-markup haskell-case-insensitive haskell-citeproc haskell-commonmark haskell-commonmark-extensions haskell-commonmark-pandoc haskell-connection haskell-data-default haskell-doclayout haskell-doctemplates haskell-emojis haskell-file-embed haskell-gridtables haskell-haddock-library haskell-hslua haskell-hslua-aeson haskell-hslua-module-doclayout haskell-hslua-module-path haskell-hslua-module-system haskell-hslua-module-text haskell-hslua-module-version haskell-http-client haskell-http-client-tls haskell-http-types haskell-ipynb haskell-jira-wiki-markup haskell-lpeg haskell-network haskell-network-uri haskell-pandoc-lua-marshal haskell-pandoc-types haskell-pretty-show haskell-random haskell-safe haskell-scientific haskell-servant-server haskell-skylighting haskell-skylighting-core haskell-split haskell-syb haskell-tagsoup haskell-temporary haskell-texmath haskell-text-conversions haskell-unicode-collation haskell-unicode-transforms haskell-wai haskell-wai-extra haskell-warp haskell-xml haskell-xml-conduit haskell-xml-types haskell-yaml haskell-zip-archive haskell-zlib haskell-tasty haskell-tasty-golden haskell-tasty-hunit haskell-tasty-lua haskell-tasty-quickcheck
🛈 Installing missing dependencies from sync database...
⚠ No such file or directory (os error 2)
🛈 Building for architecture any...

==> ERROR: An unknown error has occurred. Exiting...
⮾ makepkg exits with non-zero status code: 1
```

Thanks for your time,
Boyang Yan

**Comment by KSXGitHub** [comment]
Can you try setting `global-settings.arch-filter` to `[x86_64]`?

**Comment by yanboyang713** [comment]
@KSXGitHub 

Same issue.
This is my YAML file.

https://github.com/yanboyang713/Meta-Scientific-Collection-PKGBUILDs/blob/main/build-pacman-repo.yaml

**Comment by KSXGitHub** [comment]
```txt
==> ERROR: An unknown error has occurred. Exiting...
```

This error message looks like something from `pacman`/`makepkg` rather than from `build-pacman-repo`. I also tried to find this string in the codebase and found none.

I've seen that you set `pacman` to `yay` in `meta-emacs`? I doubt that `yay` interface is 100% compatible with `pacman`. I've never actually tried setting `pacman` with any AUR helper either, because even if it succeeds, the resulting repository is still unusable with `pacman` as some packages depend on AUR package that don't appear in the repo. What I did instead was to use `build-pacman-repo init` (with `init-aur-builder.yaml` as the manifest file) to clone all the AUR packages to a directory and then build all of them. Be aware that `build-pacman-repo init` would overwrite `build-pacman-repo.yaml` so you probably have to create 2 directories for the 2 manifest files (and insert `cd` into both steps).

In the future, I'll probably add `members` fields to `init-aur-builder.yaml` to make combining AUR packages and custom PKGBUILDs more convenient.

**Comment by yanboyang713** [comment]
@KSXGitHub Thanks,
I changed to yay because meta-emacs got three dependencies from AUR, which are emacs-pdf-tools-git, mu mbsync-git.

Maybe, for now, I can use the "install" script as a workaround. What do you think the "install" script is a good workaround?

yay's cache is different than pacman's cache:
https://herbort.me/posts/automatically-cleaning-pacman-and-yay-cache-in-arch-linux/

**Comment by KSXGitHub** [comment]
> meta-emacs got three dependencies from AUR

Just three? Are these packages also depend on other AUR packages? If not, I suggest manually cloning these 3 packages (using `git`, `build-pacman-repo init` would be overkill here) and then add them to members. But if they also depend on a network of many other packages, then `build-pacman-repo init` is absolutely necessary. [(BTW, this is how `build-pacman-repo init` is used)](https://github.com/KSXGitHub/aur-packages-builder)

Anyway, I think having packages in your repository being dependent on the AUR is a **bad idea**. The best practice is to build the AUR dependencies and add them to your repo. This way, only `pacman` would be necessary to install packages from your repo, and no AUR helper would be needed. I also suspect that `yay` would refuse to install AUR dependencies for repo packages anyway, though I haven't tested it.

**Comment by KSXGitHub** [comment]
**UPDATE:** I just noticed that I mistakenly wrote `build-pacman-repo init` instead of `build-pacman-repo init-aur-builder` so I corrected it.

**Comment by KSXGitHub** [comment]
@yanboyang713 Wait a minute!

> which are emacs-pdf-tools-git, mu mbsync-git.

Why must you depend on `-git` packages specifically? Why not just `emacs-pdf-tools` and `mbsync`? Even if those names don't exist, the AUR helper can still resolve to `-git` names because the `-git` packages have already set the `provides` field.

Anyway, it looks like you have to write your own stable (without `-git`) PKGBUILDs that provides `emacs-pdf-tools` and `mbsync` and place it in `members` directory. I suggest creating `meta-emacs-pdf-tools` and `meta-mbsync` (or whatever names you so choose as long as it's not literally `emacs-pdf-tools` and `mbsync`) and set their `provides` to `emacs-pdf-tools` and `mbsync` respectively.

**Comment by yanboyang713** [comment]
@KSXGitHub ok, thanks so much. I am still looking at what you said now.

**Comment by yanboyang713** [comment]
Hello @KSXGitHub,

I got your points now. I am moving some of the AUR packages to my own repo.
But, I faced another issue which shows "package architecture is not valid", details are below.

PKGBUILD file at *https://github.com/yanboyang713/Meta-Scientific-Collection-PKGBUILDs/blob/main/members/meta-mbsync/PKGBUILD*

Do you know the reason why? Thanks for your time.

```
==> Installing package meta-mbsync-git with pacman -U...
error: failed to prepare transaction (package architecture is not valid)
loading packages...
:: package meta-mbsync-git-1306.65cd442-1-i686 does not have a valid architecture
```

Boyang Yan

**Comment by KSXGitHub** [comment]
1. All `*-git` packages should be renamed to `meta-*` without the `-git` suffix. This includes their `pkgname`.
2. The `-git` suffix should be removed from `pkgname`.
3. All `pkgver()` functions should be removed.
4. The `pkgver` field (not function) should be set to something else, for example: `2022.09.23`.
5. Remove `i686` from `arch`, leaving only `x86_64`.

**Comment by yanboyang713** [comment]
@KSXGitHub Thanks you so much.

got it
