### ISSUE TITLE
github Action Upload packages step should change

### ISSUE THREAD

**Issue by yanboyang713** [pacman-repo-builder/pacman-repo-builder#58]
Hello,

Good day to you.

When zst file too large more than 100MB, could not push to repository successful.

I think github Action Upload packages step should change. ERROR MSG below.

```
remote: error: Trace: 4d2abe998696140b6fa5802a3273d87cf84ad8f03a88272202e88f9ebdd70ea5        
remote: error: See http://git.io/iEPt8g for more information.        
remote: error: File repo/brave-bin-1:1.46.144-1-x86_64.pkg.tar.zst is 1[38](https://github.com/yanboyang713/Meta-Scientific-Collection-PKGBUILDs/actions/runs/3721712698/jobs/6312050102#step:8:39).23 MB; this exceeds GitHub's file size limit of 100.00 MB        
remote: error: GH001: Large files detected. You may want to try Git Large File Storage - https://git-lfs.github.com./        
To https://github.com/yanboyang713/Meta-Scientific-repository.git
 ! [remote rejected] main -> main (pre-receive hook declined)
error: failed to push some refs to 'https://github.com/yanboyang713/Meta-Scientific-repository.git'
Error: Process completed with exit code 1.
```
Also, I think Clone target repository step need add
```
git submodule update --init --recursive
```

Make easier to use AUR as submodule

**Comment by KSXGitHub** [comment]
This is an inherent limitation that GitHub intentionally set up. The only way to overcome this limitation is to not use GitHub, for example:
* You may set up your own local file storage server (recommended if you have the time, money, and resources).
* You may set up your own local git server (not recommended, a regular file server is better).
* You may use 3rd party cloud providers such as AWS, MEGA, Dropbox, Google Drive, Linode, etc. to set up your own file storage server.
* You may check GitLab and other git providers to see if they allow bigger sizes.
* You may use Git LFS by GitHub.

The GitHub Action (pacman-repo-builder/action) does it concern itself with how you publish your packages to your chosen server. The error you see is not caused by the action, but rather, it was caused by the code you passes to `with.command` under `use: pacman-repo-builder/action`. You may adapt or change your `with.command` to any of the method I mentioned above.

> Also, I think Clone target repository step need add
> 
> ```
> git submodule update --init --recursive
> ```
> 
> Make easier to use AUR as submodule

This too, can be implemented by the code inside your `with.command`.

**Comment by yanboyang713** [comment]
Hello @KSXGitHub,

Thanks for your reply,

I found Azure Data Lake Gen2 is a good choice for personal repo with low price.

Azure Blob with Github Action
Upload
https://github.com/marketplace/actions/azure-blob-storage-upload

Download
https://github.com/marketplace/actions/azure-blob-storage-download-blob

Thanks for your time.
